### ISSUE TITLE
metabox custom fields and size

### ISSUE THREAD

**Issue by ysupr** [chrisblackwell/wordpress-custom-post-type#1]
Hi, Chris, 

Is there any parameters to set metabox more customizable? 
i see that you used simple parameter like 
```
array('name' => 'Retail Price', 'class' => 'half-width'),
```

is there any class other than half-width? 
and maybe change the field type? 

thanks

**Comment by chrisblackwell** [comment]
Hi @ysupr 

You can pass any class or type you want. For example:

```array('name' => 'Sale Date', 'type' => 'date', class' => 'datepicker')```

You would then just put your CSS for `.datepciker` in your admin stylesheet.

**Comment by ysupr** [comment]
oh ok then, i think it was provided on your library :)
